# .github/workflows/pages.yml  (name doesn’t matter as long as it’s *.yml)
name: Build & deploy to GitHub Pages
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If you **build**, add it here.  Otherwise delete these two lines.
      # - run: npm ci && npm run build
      #   env:
      #     VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

      # Path where the HTML lives.
      # Change "." to "dist" if you kept the build step above.
      - name: Substitute Firebase placeholders
        run: |
          TARGET="."        # or TARGET="dist"
          find "$TARGET" -type f \( -name '*.html' -o -name '*.js' \) -print0 |
          xargs -0 sed -i \
            -e 's#__FIREBASE_API_KEY__#${{ secrets.FIREBASE_API_KEY }}#g' \
            -e 's#__FIREBASE_AUTH_DOMAIN__#${{ secrets.FIREBASE_AUTH_DOMAIN }}#g' \
            -e 's#__FIREBASE_PROJECT_ID__#${{ secrets.FIREBASE_PROJECT_ID }}#g'

      # *** Diagnostic: keep while testing ***
      - name: Peek at first few lines
        run: head -n 15 ./index.html   # adjust to dist/index.html if needed

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .   # or dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
